#!/usr/bin/python

import commands
import sys

def main():
	usage = "Usage: rfind <filename>"
	args = sys.argv

	if len(args) < 2:
		print "error: not enough arguments supplied"
		print usage
		exit(1)
	if len(args) > 2:
		print "error: too many arguments supplied"
		print usage
		exit(1)

	status, output = commands.getstatusoutput("ls -R | grep " + args[1])

	lines = output.split('\n')
	for line in lines:
		status, path = commands.getstatusoutput("find . -name '" + line + "'")
		print path

main()
